{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"kwant_install.ipynb","provenance":[],"collapsed_sections":[]},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":8,"metadata":{"id":"wA54HD2YQRoY","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1651085597982,"user_tz":-120,"elapsed":3774,"user":{"displayName":"Jakub Korsak","userId":"04139474178136392181"}},"outputId":"08529849-4a2e-4dad-94a4-642efb2aba81"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}],"source":["import os, sys\n","from google.colab import drive\n","drive.mount('/content/drive', force_remount=True)\n","nb_path = '/content/notebooks'\n","os.remove(nb_path)\n","os.symlink('/content/drive/My Drive/Colab Notebooks', nb_path)\n","if nb_path not in sys.path:\n","  sys.path.insert(5, nb_path)\n"]},{"cell_type":"code","source":["!pip install --target=$nb_path numpy\n","!pip install --target=$nb_path kwant"],"metadata":{"id":"syCMOG3IRPep","colab":{"base_uri":"https://localhost:8080/","height":1000},"outputId":"f6242865-ae20-4e7b-ddb0-8bb7492171b5","executionInfo":{"status":"ok","timestamp":1651085629499,"user_tz":-120,"elapsed":19277,"user":{"displayName":"Jakub Korsak","userId":"04139474178136392181"}}},"execution_count":9,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting numpy\n","  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)\n","Installing collected packages: numpy\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","tensorflow 2.8.0 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.\n","datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.\n","albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.\u001b[0m\n","Successfully installed numpy-1.21.6\n","\u001b[31mERROR: Exception:\n","Traceback (most recent call last):\n","  File \"/usr/lib/python3.7/shutil.py\", line 566, in move\n","    os.rename(src, real_dst)\n","FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-target-7zvkp2b5/lib/python/numpy-1.21.6.dist-info' -> '/content/notebooks/numpy-1.21.6.dist-info'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py\", line 180, in _main\n","    status = self.run(options, args)\n","  File \"/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py\", line 199, in wrapper\n","    return func(self, options, args)\n","  File \"/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py\", line 450, in run\n","    options.target_dir, target_temp_dir, options.upgrade\n","  File \"/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py\", line 509, in _handle_target_dir\n","    target_item_dir\n","  File \"/usr/lib/python3.7/shutil.py\", line 577, in move\n","    symlinks=True)\n","  File \"/usr/lib/python3.7/shutil.py\", line 324, in copytree\n","    os.makedirs(dst)\n","  File \"/usr/lib/python3.7/os.py\", line 223, in makedirs\n","    mkdir(name, mode)\n","FileNotFoundError: [Errno 2] No such file or directory: '/content/notebooks/numpy-1.21.6.dist-info'\u001b[0m\n"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["numpy"]}}},"metadata":{}},{"output_type":"stream","name":"stdout","text":["Collecting kwant\n","  Using cached kwant-1.4.3-cp37-cp37m-linux_x86_64.whl\n","Collecting numpy>=1.11.0\n","  Using cached numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)\n","Collecting tinyarray>=1.2\n","  Using cached tinyarray-1.2.4-cp37-cp37m-linux_x86_64.whl\n","Collecting scipy>=0.17.0\n","  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)\n","Installing collected packages: numpy, tinyarray, scipy, kwant\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","tensorflow 2.8.0 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.\n","datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.\n","albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.\u001b[0m\n","Successfully installed kwant-1.4.3 numpy-1.21.6 scipy-1.7.3 tinyarray-1.2.4\n","\u001b[31mERROR: Exception:\n","Traceback (most recent call last):\n","  File \"/usr/lib/python3.7/shutil.py\", line 566, in move\n","    os.rename(src, real_dst)\n","FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-target-cbjn27uk/lib/python/numpy-1.21.6.dist-info' -> '/content/notebooks/numpy-1.21.6.dist-info'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py\", line 180, in _main\n","    status = self.run(options, args)\n","  File \"/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py\", line 199, in wrapper\n","    return func(self, options, args)\n","  File \"/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py\", line 450, in run\n","    options.target_dir, target_temp_dir, options.upgrade\n","  File \"/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py\", line 509, in _handle_target_dir\n","    target_item_dir\n","  File \"/usr/lib/python3.7/shutil.py\", line 577, in move\n","    symlinks=True)\n","  File \"/usr/lib/python3.7/shutil.py\", line 324, in copytree\n","    os.makedirs(dst)\n","  File \"/usr/lib/python3.7/os.py\", line 223, in makedirs\n","    mkdir(name, mode)\n","FileNotFoundError: [Errno 2] No such file or directory: '/content/notebooks/numpy-1.21.6.dist-info'\u001b[0m\n"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["numpy"]}}},"metadata":{}}]},{"cell_type":"code","source":[""],"metadata":{"id":"O05eC_hiTI8F"},"execution_count":null,"outputs":[]}]}